# Generated by Django 4.2 on 2023-04-12 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NectarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='nectar source date')),
                ('source', models.CharField(choices=[('F', 'Flowers'), ('T', 'Tree Sap'), ('Ft', 'Fruit'), ('Ot', 'Others')], default='F', max_length=2)),
                ('butterfly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.butterfly')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('blooming_season', models.CharField(max_length=100)),
                ('butterfly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.butterfly')),
            ],
        ),
    ]
