# Generated by Django 4.2 on 2023-04-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_nectarsource_flower'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterfly',
            name='flowers',
            field=models.ManyToManyField(related_name='butterflies', to='main_app.flower'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='butterfly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nectar_sources', to='main_app.butterfly'),
        ),
    ]
