# Generated by Django 4.2 on 2023-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_butterfly_flowers_alter_flower_butterfly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='butterfly',
        ),
        migrations.AlterField(
            model_name='butterfly',
            name='flowers',
            field=models.ManyToManyField(to='main_app.flower'),
        ),
        migrations.AlterField(
            model_name='nectarsource',
            name='source',
            field=models.CharField(choices=[('B', 'Blossom'), ('T', 'Tree Sap'), ('Ft', 'Fruit'), ('Ot', 'Others')], default='B', max_length=2),
        ),
    ]
