# Generated by Django 4.2 on 2023-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_flower_butterfly_alter_butterfly_flowers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterfly',
            name='color',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
